# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "moona"
  s.version = "0.0.1"

  s.authors = ["Dan Langevin"]
  s.date = "2012-10-05"
  s.description = "Google Analytics and integration"
  s.email = "dan.langevin@lifebooker.com"
  s.homepage = "http://github.com/LifebookerInc/moona"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.summary = "Google Analytics"

  s.required_rubygems_version = ">= 1.3.6"
  s.rubyforge_project         = "jquery-rails"

  s.files        = `git ls-files`.split("\n")
  s.executables  = `git ls-files -- bin/*`.split("\n").map { |f| File.basename(f) }

  s.add_dependency(%q<activesupport>, [">= 0"])
  s.add_dependency(%q<celluloid>, [">= 0"])
  s.add_dependency(%q<rest-client>, [">= 0"])
  s.add_dependency(%q<json>, [">= 0"])
  s.add_dependency(%q<google-api-client>, [">= 0"])

end

